// react-demo/src/components/Notes/note-add.tsx
import { SyntheticEvent } from "react";
import { DTONote } from "../../types/note";

type Props = {
    add: (note: DTONote) => void;
};

export function NoteAdd({ add }: Props) {
    const handleSubmit = (ev: SyntheticEvent) => {
        ev.preventDefault();
        const form = ev.target as HTMLFormElement;

        const newNote: DTONote = {
            title: (form.elements.namedItem("title") as HTMLInputElement).value,
            content: (form.elements.namedItem("content") as HTMLInputElement)
                .value,
            isImportant: false,
        };

        console.log(newNote);
        add(newNote);
    };

    return (
        <form aria-label="add-note" onSubmit={handleSubmit}>
            <legend>Añadir nota</legend>
            <input
                type="text"
                name="title"
                placeholder="Describe la nota"
                required
            />
            <input
                type="text"
                name="content"
                placeholder="Contenido de la nota"
                required
            />
            <button type="submit">Añadir</button>
        </form>
    );
}

// ng-demo/src/app/components/note.add/note.add.component.ts
import { Component, EventEmitter, inject, Output } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { DTONote } from "../../types/note";

@Component({
    selector: "cas-note-add",
    imports: [ReactiveFormsModule],
    template: `
        <h2>Añadir nota</h2>
        <form class="note-form" [formGroup]="noteForm" (ngSubmit)="onSubmit()">
            <label for="title">Título</label>
            <input
                type="text"
                id="title"
                name="title"
                placeholder="Título"
                formControlName="title"
            />
            @if (
                noteForm.get("title")?.invalid && noteForm.get("title")?.touched
            ) {
                @if (noteForm.get("title")?.errors?.["required"]) {
                    <p>El campo es requerido</p>
                } @else if (noteForm.get("title")?.errors?.["minlength"]) {
                    <p>La longitud mínima es de 3 caracteres</p>
                }
            }

            <label for="description">Descripción</label>
            <input
                id="description"
                name="description"
                placeholder="Descripción"
                formControlName="description"
            />

            @if (
                noteForm.get("description")?.invalid &&
                noteForm.get("description")?.touched
            ) {
                @if (noteForm.get("description")?.errors?.["required"]) {
                    <p>El campo es requerido</p>
                } @else if (
                    noteForm.get("description")?.errors?.["minlength"]
                ) {
                    <p>La longitud mínima es de 3 caracteres</p>
                }
            }
            <button type="submit" [disabled]="noteForm.invalid">Añadir</button>
        </form>
    `,
    styles: ``,
})
export class NoteAddComponent {
    @Output() addNoteEvent: EventEmitter<DTONote> = new EventEmitter<DTONote>();
    fb = inject(FormBuilder);
    noteForm = this.fb.group({
        title: ["", [Validators.required, Validators.minLength(3)]],
        description: ["", [Validators.required, Validators.minLength(3)]],
    });

    onSubmit() {
        if (!this.noteForm.value.title || !this.noteForm.value.description) {
            return;
        }

        const newNote: DTONote = {
            title: this.noteForm.value.title,
            description: this.noteForm.value.description,
            isImportant: false,
        };
        console.log(newNote);
        this.addNoteEvent.next(newNote);
        this.noteForm.reset();
    }
}
