// ng-demo/src/app/components/note.item/note.item.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { Note } from "../../types/note";

@Component({
    selector: "cas-note-item",
    imports: [],
    template: `
        <input type="checkbox" [checked]="note.isImportant" 
        (change)="handleChange()" />
        <p class="note-title">
            {{ note.title }}
        </p>
        <button type="button" (click)="handleClick()">Borrar</button>
    `,
    styles: ``,
})
export class NoteItemComponent {
    @Input() note!: Note;
    @Output() deleteNoteEvent = new EventEmitter<Note>();
    @Output() updateNoteEvent = new EventEmitter<Note>();

    handleClick() {
       this.deleteNoteEvent.emit(this.note);
    }

    handleChange() {
        this.note.isImportant = !this.note.isImportant;
        this.updateNoteEvent.emit(this.note);
    }

}

// react-demo/src/components/Notes/note-item.tsx
import { Note } from "../../types/note";

type Props = {
    note: Note;
    deleteNote: (id: string) => void;
    updateNote: (note: Note) => void;
};

export function NoteItem({ note, deleteNote, updateNote }: Props) {
    const handleDelete = () => {
        console.log("Eliminar nota", note.id);
        deleteNote(note.id);
    };

    const handleChange = () => {
        console.log("Cambiar nota", note.id);
        const updatedNote = { ...note, isImportant: !note.isImportant };
        updateNote(updatedNote);
    };

    const template = (
        <div className="note-item">
            <h2>{note.title}</h2>
            <p>{note.content}</p>
            <p>
                <input type="checkbox" checked={note.isImportant} 
                    onChange={handleChange}
                />{" "}
                {note.isImportant ? "Importante" : "No importante"}
            </p>
            <button onClick={handleDelete}>Eliminar</button>
        </div>
    );
    return template;
}
